/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnuaireRouteImport } from './routes/annuaire'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as ConseilsRouteImport } from './routes/conseils'
import { Route as OrientationRouteImport } from './routes/orientation'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as ProRouteImport } from './routes/pro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuaireRoute = AnnuaireRouteImport.update({
  id: '/annuaire',
  path: '/annuaire',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilsRoute = ConseilsRouteImport.update({
  id: '/conseils',
  path: '/conseils',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientationRoute = OrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annuaire': typeof AnnuaireRoute
  '/cabinet': typeof CabinetRoute
  '/conseils': typeof ConseilsRoute
  '/orientation': typeof OrientationRoute
  '/parcours': typeof ParcoursRoute
  '/pro': typeof ProRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annuaire': typeof AnnuaireRoute
  '/cabinet': typeof CabinetRoute
  '/conseils': typeof ConseilsRoute
  '/orientation': typeof OrientationRoute
  '/parcours': typeof ParcoursRoute
  '/pro': typeof ProRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annuaire': typeof AnnuaireRoute
  '/cabinet': typeof CabinetRoute
  '/conseils': typeof ConseilsRoute
  '/orientation': typeof OrientationRoute
  '/parcours': typeof ParcoursRoute
  '/pro': typeof ProRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annuaire'
    | '/cabinet'
    | '/conseils'
    | '/orientation'
    | '/parcours'
    | '/pro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annuaire'
    | '/cabinet'
    | '/conseils'
    | '/orientation'
    | '/parcours'
    | '/pro'
  id:
    | '__root__'
    | '/'
    | '/annuaire'
    | '/cabinet'
    | '/conseils'
    | '/orientation'
    | '/parcours'
    | '/pro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnuaireRoute: typeof AnnuaireRoute
  CabinetRoute: typeof CabinetRoute
  ConseilsRoute: typeof ConseilsRoute
  OrientationRoute: typeof OrientationRoute
  ParcoursRoute: typeof ParcoursRoute
  ProRoute: typeof ProRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire': {
      id: '/annuaire'
      path: '/annuaire'
      fullPath: '/annuaire'
      preLoaderRoute: typeof AnnuaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils': {
      id: '/conseils'
      path: '/conseils'
      fullPath: '/conseils'
      preLoaderRoute: typeof ConseilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientation': {
      id: '/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof OrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnuaireRoute: AnnuaireRoute,
  CabinetRoute: CabinetRoute,
  ConseilsRoute: ConseilsRoute,
  OrientationRoute: OrientationRoute,
  ParcoursRoute: ParcoursRoute,
  ProRoute: ProRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
