/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnuaireRouteImport } from './routes/annuaire'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as ConnexionMedecinRouteImport } from './routes/connexion-medecin'
import { Route as ConseilsRouteImport } from './routes/conseils'
import { Route as OrientationRouteImport } from './routes/orientation'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as CabinetAccueilRouteImport } from './routes/cabinet/accueil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuaireRoute = AnnuaireRouteImport.update({
  id: '/annuaire',
  path: '/annuaire',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionMedecinRoute = ConnexionMedecinRouteImport.update({
  id: '/connexion-medecin',
  path: '/connexion-medecin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConseilsRoute = ConseilsRouteImport.update({
  id: '/conseils',
  path: '/conseils',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientationRoute = OrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetAccueilRoute = CabinetAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => CabinetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annuaire': typeof AnnuaireRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/connexion-medecin': typeof ConnexionMedecinRoute
  '/conseils': typeof ConseilsRoute
  '/orientation': typeof OrientationRoute
  '/parcours': typeof ParcoursRoute
  '/suivi': typeof SuiviRoute
  '/cabinet/accueil': typeof CabinetAccueilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annuaire': typeof AnnuaireRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/connexion-medecin': typeof ConnexionMedecinRoute
  '/conseils': typeof ConseilsRoute
  '/orientation': typeof OrientationRoute
  '/parcours': typeof ParcoursRoute
  '/suivi': typeof SuiviRoute
  '/cabinet/accueil': typeof CabinetAccueilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annuaire': typeof AnnuaireRoute
  '/cabinet': typeof CabinetRouteWithChildren
  '/connexion-medecin': typeof ConnexionMedecinRoute
  '/conseils': typeof ConseilsRoute
  '/orientation': typeof OrientationRoute
  '/parcours': typeof ParcoursRoute
  '/suivi': typeof SuiviRoute
  '/cabinet/accueil': typeof CabinetAccueilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annuaire'
    | '/cabinet'
    | '/connexion-medecin'
    | '/conseils'
    | '/orientation'
    | '/parcours'
    | '/suivi'
    | '/cabinet/accueil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annuaire'
    | '/cabinet'
    | '/connexion-medecin'
    | '/conseils'
    | '/orientation'
    | '/parcours'
    | '/suivi'
    | '/cabinet/accueil'
  id:
    | '__root__'
    | '/'
    | '/annuaire'
    | '/cabinet'
    | '/connexion-medecin'
    | '/conseils'
    | '/orientation'
    | '/parcours'
    | '/suivi'
    | '/cabinet/accueil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnuaireRoute: typeof AnnuaireRoute
  CabinetRoute: typeof CabinetRouteWithChildren
  ConnexionMedecinRoute: typeof ConnexionMedecinRoute
  ConseilsRoute: typeof ConseilsRoute
  OrientationRoute: typeof OrientationRoute
  ParcoursRoute: typeof ParcoursRoute
  SuiviRoute: typeof SuiviRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire': {
      id: '/annuaire'
      path: '/annuaire'
      fullPath: '/annuaire'
      preLoaderRoute: typeof AnnuaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion-medecin': {
      id: '/connexion-medecin'
      path: '/connexion-medecin'
      fullPath: '/connexion-medecin'
      preLoaderRoute: typeof ConnexionMedecinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conseils': {
      id: '/conseils'
      path: '/conseils'
      fullPath: '/conseils'
      preLoaderRoute: typeof ConseilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientation': {
      id: '/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof OrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/accueil': {
      id: '/cabinet/accueil'
      path: '/accueil'
      fullPath: '/cabinet/accueil'
      preLoaderRoute: typeof CabinetAccueilRouteImport
      parentRoute: typeof CabinetRoute
    }
  }
}

interface CabinetRouteChildren {
  CabinetAccueilRoute: typeof CabinetAccueilRoute
}

const CabinetRouteChildren: CabinetRouteChildren = {
  CabinetAccueilRoute: CabinetAccueilRoute,
}

const CabinetRouteWithChildren =
  CabinetRoute._addFileChildren(CabinetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnuaireRoute: AnnuaireRoute,
  CabinetRoute: CabinetRouteWithChildren,
  ConnexionMedecinRoute: ConnexionMedecinRoute,
  ConseilsRoute: ConseilsRoute,
  OrientationRoute: OrientationRoute,
  ParcoursRoute: ParcoursRoute,
  SuiviRoute: SuiviRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
